#!/usr/bin/env bash
# Installs Nginx web server on the server
#+ Nginx should be listening to port 80
#+ When querying nginx at it's root using curl it
#+	must return a page with a sting "Hello World!
#+ configures a new Ubuntu machine to respect above requirements
sudo apt-get update && sudo apt-get install nginx -y

sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html

sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
