#!/usr/bin/env bash
# Bash script that displays ls Where only the part of the name after the first dash is displayed

file="./Bestschool"
if [ -e $file ]
then 
        echo "Bestschool file exists"
        if [ -s $file ]
        then
                echo "Bestschool file is not empty"
        else
		            echo "Bestschool file is empty"
	      fi
        if [ -f $file ]
        then
                echo "Bestschool is a regular file"
        fi
	
else
        echo "Bestschool file does not exist"
fi